library(dplyr)
library(readr)
library(ggplot2)
library(tidyr)

################################################################################
############### Function that counts of the number of state related topics including Twitter Terms
################################################################################
get_n_state_topics <- function(result) {

  library(stm)
  
  single_word_states <- c('alabama', 'alaska', 'arizona', 'arkansas', 'california', 'colorado', 'connecticut',
                          'delaware', 'florida', 'georgia', 'hawaii', 'idaho', 'illinois', 'indiana', 'iowa', 'kansas',
                          'kentucky', 'louisiana', 'maine', 'maryland', 'massachusetts', 'michigan', 'minnesota', 'mississippi', 'missouri',
                          'montana', 'nebraska', 'nevada', 'ohio', 'oklahoma', 'oregon', 'pennsylvania',  
                          'tennessee', 'texas', 'utah', 'vermont', 'virginia', 'washington', 'wisconsin', 'wyoming')
  
  two_word_states <- c('new hampshire', 'new jersey', 'new mexico', 'new york', 'north carolina',
                       'north dakota', 'rhode island', 'south carolina', 'south dakota', 'west virginia')
  
  two_word_states_list <- strsplit(two_word_states, ' ')
  
  abbreviations <- c('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA',
                     'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC',
                     'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY')
  
  abbreviations <- tolower(abbreviations)
  
  twitter_terms <- c("@senatorserrano", "@marcoscrespo85", "@michaellesolage", "@nysenate", "@vpichardo86",
                     "@jeffreydinowitz", "@rjackson_nyc", "@harveyforny", "@cndelarosa", "@dickgottfried",
                     "@amdanquart", "#repeal50a", "@senatorpersaud", "@nyslabor", "@govmarkdayton",
                     "@minnesotadfl", "@mnhousedfl", "dfl", "@morrison4mn", "@mattkleinsd52",
                     "@bradtabke", "@educationmn", "@tim_walz", "@stowydad", "@shabbosgoy",
                     "@mnhouseinfo", "@senatedfl", "#mnhouse", "@mnsrc", "@alicemann4house",
                     "@mikehowardmn", "@jeffreyhayden", "@ctgop", "@ctsenatedems", "@ctnewsjunkie",
                     "@ctsenategop", "@senatorduff", "@1980reagan", "@andymanar", "arkansans",
                     "@jimhendren1", "#arnews", "@arkansassenate", "@robybrock", "@arkansashouse",
                     "@danbluenc", "@christyclarknc", "@ilsendems", "@jmnemes", "@kyhousegop",
                     "@alvarado4senate", "#kyga19", "#kyga18", "@repkoenig", "@kysenategop",
                     "@kychamber", "#kyga17", "@kellibutleraz", "#ld28", "@jenlongdon",
                     "@jennifer_pawlik", "@iselablancaz", "@heathercarteraz", "@azhousedems", "@jeffweninger",
                     "@repbryancutler", "@palegblkcaucus", "@repkinsey", "@senatorkristin", "#pasenate",
                     "#pahouse", "@senlisabaker", "@pasenategop", "@senatoraument", "@pahousedems",
                     "@senatormartinpa", "@pcntv", "@senbartolotta", "@secretarylevine", "#pabudget",
                     "#wpial", "@aaronmvega", "@sabadosama", "@reppaulmark", "@adamghinds",
                     "@ma_bllc", "#westernma", "@projectbread", "@marjoriedecker", "@senjasonlewis",
                     "@repjimoday", "@jayasheohed", "@massltgov", "#maedu", "#worcester",
                     "@karenspilka", "@senstan", "@tommyvitolo", "#matreas", "@masscultural",
                     "@rob_bradley", "@jimmypatronis", "@flsenate", "@billgalvano", "@anitere_flores",
                     "@jamesgrantfl", "@peterschorschfl", "@danielrbenson", "@valerie_huttle", "#mdga19",
                     "@speakerbusch", "#neleg", "@curtisherteljr", "@krizekforva", "@marksicklesva",
                     "@vvfordelegate", "@marcussimon", "@hopeforvirginia", "@barbarafavola", "@delterrykilgore",
                     "@jonesjay", "@bluevirginia", "#va10", "#covid19ma", "@massdcr",
                     "@massdph", "@cindyfriedmanma", "@repsmitty", "@senmikemoore", "#senbudget",
                     "#intheberkshires", "@annegobi", "@senjoanlovely", "@massdot", "@senrodrigues",
                     "@senjehlen", "@senbrucetarr", "@dianadizoglio", "@skpeake", "@senatormikerush",
                     "@capublichealth", "@jimwoodad2", "@wiassemblygop", "#foxconn", "#wiworking",
                     "@robvescovo", "@meaccoleman", "@bobondermo", "@calebrowden", "@tamigouveiama",
                     "@barber4staterep", "@ldforry", "@jonechols", "@agounardes", "@nysendems",
                     "@nynurses", "@davidcarlucci", "@nycschools", "@karinesreyes87", "@sarbetter",
                     "@jamaaltbailey", "@cityandstateny", "@senkennedy", "@liunewyork", "@nysut",
                     "@bobby4brooklyn", "@davidvitter", "@wahousegop", "#waelex", "@iowahousedems",
                     "#nhsen", "@nhhouseofreps", "#mtnews", "@zenzinger_atoz", "@alecgarnett",
                     "#edcolo", "@repjanetbuckner", "@tkth", "@jovanmelton", "@stevefenberg",
                     "@jerrysonnenberg", "@matthewogray", "@jeffbridges", "@jeffmbourne", "@mikemullin4va",
                     "@clarkcountysch", "@edgarfloresnv", "#rgv", "@repdennisbonnen", "@toddahunter",
                     "@nvgopassembly", "#askwaleg", "#mdga18", "#mdga17", "@mddems",
                     "@ericluedtke", "@mkorman", "#mdga2020", "@md_sbe", "@electcorymccray",
                     "@aravellasimotas", "@leroycomrie", "@assemblymanjoe", "@fernandez4ny", "@cpeoplesstokes",
                     "@dandaley", "@oscarjb2", "@richardcorcoran", "#nced", "@repdavidrlewis",
                     "@johnbellnc", "@ncdhhs", "@juliefornc", "@katemcgeeaz", "#az",
                     "@brahmresnik", "#kyga16", "@senatorjimmy", "#kyga15", "@urena",
                     "#nhhouse", "@nhyoungdems", "@thenhsenate", "@fldeo", "@ambichotte",
                     "@vanessalgibson", "@luissepulvedany", "#nys", "@rubendiazjr", "@sengriffo",
                     "@senatormetzger", "@asmsantabarbara", "@jamestedisco", "@cappressroom", "#mnsen",
                     "#oneminnesota", "#teammercado", "@farmerforflsen", "@flsenatedems", "@kionnemcghee",
                     "@flgopmajority", "#wvlegis", "@hoppykercheval", "@wvhouse", "#wvpol",
                     "@morriseywv", "@philkabler", "@senatorlanza", "#roc", "@tmftx",
                     "@drewspringer", "@sarahforhd134", "@anahdztx", "@eddiefortexas", "@repthierry146",
                     "@txworkforce", "@ginaforaustin", "@texasdshs", "@celiaisrael", "@texashouse",
                     "@judgeclayj", "@houstonisd", "@texashdc", "@vote4ina", "@txlege",
                     "@gfcoleman", "@diegobernaltx", "@scottbraddock", "@senroycewest", "@txchuy",
                     "@terrycanales40", "@donnahowardtx", "@repchriswelch", "@toddkaminsky", "@annamkaplan",
                     "@azhousegop", "@azsenategop", "pima", "@azsenatedems", "@diego4justice",
                     "@engelforarizona", "@mitziepstein", "@drrandyfriese", "@votewarren", "@nmhousedems",
                     "@abqjournal", "@senpadilla", "@javierfornm", "#mht", "@marcmolinaro",
                     "@senatorgeneyaw", "@paagriculture", "@gmjohnsonnj", "@andrewzwicker", "@pamlampitt1",
                     "@vincemazzeo", "#argop", "@glencasada", "@jeremyfaison4tn", "@tnhousegop",
                     "@williamlamberth", "@ltgovmcnally", "@tnsenategop", "#govotetn", "@senfrankniceley",
                     "@csexton25", "@mattshaheen", "@loiskolkhorst", "https://t.co/u6b3khqu7x", "@gasenatedems",
                     "#gahouse", "@bucyfortexas", "@dadephelan", "@votegiovanni", "@angiehatton16",
                     "@lgwillner", "@bryanavilafl", "@flchamber", "#3totweet", "@sherylcole1",
                     "@whitmire_john", "@menendez4texas", "@danmartinez305", "#maconvos", "@mawomenscaucus",
                     "@deblavender", "@saraformissouri", "@iahousegop", "@nmsenatedems", "#abq",
                     "@sencamward", "@jdmesnard", "@jennjermaine", "#azsenate", "@antoniohayes40",
                     "@baltcityschools", "@senbillferg", "@senatormccray", "@lukebroadwater", "@willcsmithjr",
                     "@jillpcarter", "@ld18dems", "@lelaalstonaz", "#algop", "@garner4senate",
                     "@ridemparty", "@iandon", "@rihouseofreps", "@senatorhughes", "@senjudyschwank",
                     "@sentonywilliams", "@senhannahbeth", "@rendon63rd", "@nancyskinnerca", "@asm_irwin",
                     "@sentoniatkins", "@ianad57", "@asmmikegipson", "#cabudget", "#ad24",
                     "@asmkevinmccarty", "@cawomenscaucus", "@robbontaca", "@ilike_mike", "@asmautumnburke",
                     "@kevinmullin", "@mgipson2014", "@assemblygop", "@portantino", "@eqca",
                     "@senatorleyva", "#ad60", "@asmtoddgloria", "@ad26mathis", "@richforrepld29",
                     "#ld29", "@rios_rebecca", "@jcpsky", "#breakthemajority", "@ncsenatedems",
                     "@ncpolicywatch", "@ncemergency", "#covid19nc", "@wileynickel", "@vaplan2018",
                     "@helmerva", "@senrhondafields", "@hannahekanema", "@mikeday4rep", "@repkatehogan",
                     "@paultuckersalem", "#waltham", "@mciccolo", "@cindycreem", "#quincy",
                     "@melindadeslatte", "@greghilburn1", "@inhousegop", "@marylandmatters", "@vatterbeary",
                     "#gasenate", "#gagop", "#backbecca", "@tndeptofhealth", "#stl",
                     "@brianontheair", "@j_hancock", "@missouritimes", "@missourigop", "#jeffcomo",
                     "@hrehder", "@dlhoskins", "@tracymccreery", "@mikeparson", "@hillformissouri",
                     "@mikecierpiot", "@kip_kendrick", "@molegdems", "@senatornasheed", "@lacyclaymo1",
                     "@speakerajones", "@smith4delegate", "@joycewoodhouse", "@harveypeeler", "#wibudget",
                     "@dhswi", "@miaforsc", "@garyclarysc", "@averygwilks", "@tommypopesc",
                     "@reptklarides", "@wahousedems", "#wyleg", "@jrosenbaum", "@senmannydiazjr",
                     "#capkillsjobs", "#orag", "@markobenshain", "@ryanfattman", "@blake_filippi",
                     "@rispeaker", "@patrickanderso_", "@lademos", "@garysimrill", "@nhhousedems",
                     "@chrissununu", "@visitnh", "@iahousedemocrat", "@iowasenate", "@lizmathis1",
                     "@palaborindustry", "@padcednews", "@padeptofed", "@senatenj", "@raleighreporter",
                     "@nuttia", "@wendyenthomas", "@timjosephsonnh", "@rennycushing", "@senswilliams",
                     "@ohhousedems", "#btv", "#vtleg", "@srothschild1", "@tomcox4ks",
                     "#flipmnsenate", "@patrickmoconnor", "@geoffduncanga", "#garepvotes", "@inhsedems",
                     "@insendems", "@davidmoon2014", "@repaustindavis", "@jonhardister", "@mikewoodard",
                     "@scottfaughn", "@senatormcdaniel", "@toth_4_texas", "@chrispaddie", "@repjamesfrank",
                     "bexar", "@dannycullinane", "@chuckbasye47", "#delaware", "@kirkpwatson",
                     "#setx", "#swfl", "@andruvolinsky", "#ihdc", "@fox13",
                     "@votesuz", "@benwinslow", "#uted", "@robertgehrke", "@melisafranzen",
                     "@cosagov", "@karynpolito", "@jasondisaacson", "@wilhelmfornh", "#sanantonio",
                     "@rhettaforhd113", "#teamina", "#statenisland", "@karleemacer", "@susanlvaldes",
                     "@rep_jimmy", "fish-wrapper", "#billerica", "dhec", "@corkyforsenate",
                     "#ndpol", "@utahsenate", "@utahreps", "@rep89", "@jessieopie",
                     "@gordonhintz", "@katbeep", "#azld2", "@senatorcosta", "@vingopal",
                     "@nickcollinsma", "#ad53", "@declanoscanlon", "@repcarolmoss", "#beavercounty",
                     "@sensharifstreet", "@hjnews", "#cambma", "@utahhousedems", "@kvnuftp",
                     "@padempolicy", "#policypoint", "#ausome", "@njassemblydems", "#mdpolitics",
                     "#akleg", "#mtleg", "@ma_senate", "#working4md", "#mnleg",
                     "#ksleg", "@danfeltesnh", "#msleg", "@pasenatedems", "#oklaed",
                     "@speakerdeleo", "#sayfie", "@pahousegop", "@mdhousedems", "#arleg",
                     "#arpx", "#utleg", "@cohousedem", "@pahealthdept", "#lalege",
                     "#nmleg", "#ksed", "#okleg", "#vtpoli", "@tednesi",
                     "#ncga", "@nhsenatedems", "@kyhousedems", "#ialegis", "#lagov",
                     "#wiright", "#orpol", "@elijahhaahr", "@larryhogan", "#utpol",
                     "@govchrissununu", "#nmpol", "@kathyprojo", "#ncpol", "#nysenate",
                     "#txlege", "@belbaltimore", "@wmur9", "#mngop", "@malctx",
                     "#waleg", "#inlegis", "oregonians", "#nvleg", "#kyga20",
                     "#coleg", "@soniachangdiaz", "@kygop", "@penndotnews", "#mogov",
                     "@mikeconnollyma", "@benallenca", "#bronx", "@debrasateam", "@risenate",
                     "#copolitics", "#iagov", "@jbeckerfinn", "@repgalonski", "@susankentmn",
                     "@chrisgturner", "#caleg", "@repfuelee", "@floridagop", "@ohiosenategop",
                     "@nikaelugardo", "@repgrove", "@nhkathysullivan", "@ericgreitens", "@saldidomenico",
                     "@nysenatorrivera", "@leachfortexas", "@nc_governor", "@vahousegop", "@asahutchinson",
                     "@jo_comerford", "@projo", "@poncho_nevarez", "@crystal_quade", "#azleg",
                     "@santiagoad53", "#nhpolitics", "@jenniferboysko", "@senatorjen", "minnesotans",
                     "@joegruters", "#ctpolitics", "#alpolitics", "#ld18", "@kdaudt",
                     "@barrettsenate", "@lopez4va", "#moleg", "@tngop", "@_ryanwinkler",
                     "@evanasmith", "@scottdibble", "#mapoli", "@govbilllee", "@henrymcmaster",
                     "@jaylivingstone", "@bgpolitics", "@ltgovflanagan", "#orleg", "@nhgop",
                     "@littlesenator", "@ohiosenatedems", "@travisfitzwater", "@dlesgar", "@donnasoucy",
                     "rauner", "@zellnor4ny", "@jessiedanielson", "@wvgop", "@wbrownsberger",
                     "@sectrehargett", "@nick_mosby", "@carolyndykema", "@senatorberger", "@govparsonmo",
                     "@repjoseoliva", "@charleneforaz", "@lougreenwald", "utahns", "nevada's",
                     "@mnhousegop", "@rajmukherji", "@pennsylvaniagov", "#tnleg", "@mihousedems",
                     "@jdistaso", "@aswmcknight", "@sendavidwatters", "@mdsenate", "@toddgloria",
                     "@gasenatepress", "@repkevinhonan", "@cal_fire", "#idleg", "@kydems",
                     "@shellyhettleman", "@nhdems", "@joeboncore", "@vahousedems", "@robbynlewis46th",
                     "@caseycagle", "@frostnhstaterep", "#bospoli", "@kycomer", "@laurafriedman43",
                     "arundel", "@speakercoughlin", "@wvgovernor", "@newsday", "@assemblydems",
                     "@nysa_majority", "@repalicepeisch", "@epmurphymn", "@asmgarcia", "@kmurphyva",
                     "loudoun", "@ryanquarlesky", "@senjohnfkeenan", "@boyd4oh_d9", "@fourpricetx",
                     "@russo4ohio", "@dianesavino", "pinellas", "@elenaparent", "schenectady",
                     "@vasenatedems", "@repdanmiller", "@pastatedept", "@courtneywatson1", "nys",
                     "@clarionledger", "@repturzai", "@davidchiu", "@jamestalarico", "@billleetn",
                     "@senshilling", "@delawareonline", "tennesseans", "@mngop", "@repjayxiong",
                     "@govlarryhogan", "@kentuckysrccc", "#netde", "@shanemassey", "@mbta",
                     "@galeabrewer", "@flhousedems", "@seanbowie", "@carolfortexas", "@cagovernor",
                     "@tnsenate", "@ericburlison", "@bradmcelhinny", "@jamescita", "@yhn",
                     "@repmichlewitz", "marylanders", "@brianjfeldman", "#wilmde", "#hounews",
                     "@insenategop", "@kathyswan147", "#capecod", "#arwx", "gwinnett",
                     "@erinmayequade", "@conservationco", "@mendezforaz", "@nchousegop", "@karlabigham",
                     "@wiltonsimpson", "@fraserfor15", "@rcproudie", "@jeffreybrandes", "@delegatemark",
                     "@kellytownsend11", "@phlchristo", "@chrissprowls", "mn's", "nebraskans",
                     "@mnhealth", "@marcrpacheco", "@brigidekelly", "#twill", "@repchynahtyler",
                     "@repdottieb4mo", "@senatorhassan", "@nchousespeaker", "@christina4rep", "@chrispappasnh",
                     "#district50", "@bradhoylman", "@brendancrighton", "arizonans", "#txed",
                     "@arizona_sos", "#ncgov", "@nathanballentin", "@ksucats96", "@kenivoryut",
                     "@chairmanbuckley", "@annettequijano", "@lucha_az", "#transferpubliclands", "@billhagertytn",
                     "@cosendem", "@wvuflu", "@nyccomptroller", "@hallforiowa", "@jayerwilliamson",
                     "@tnsenatedems", "@bluestein", "@delarianakelly", "@seanscanlonct", "berks",
                     "@bbierschbach", "sununu", "@trammellbob", "#gadems", "@senfitzgerald",
                     "#pgh", "@heather_edelson", "@repdanhunt", "#gapol", "@jamesskoufis",
                     "@georgiademocrat", "@massgovernor", "@kychrismcdaniel", "@jillschupp", "@ohiogop",
                     "@moodyforelpaso", "#stribpol", "@govrauner", "#rva", "@repharrisky",
                     "@va_gop", "@nvdems", "@kysenatepres", "@marty_walsh", "@pwoodreporter",
                     "@kumarbarve", "@barry_finegold", "@cornejoformo", "@melissahortman", "@fla_pol",
                     "#maleg", "@lizolson218", "@morganmcgarvey", "@govstitt", "@njsenatepres",
                     "@tamu", "@nhcardona603", "@ruthforhouse", "@lcharkoudian", "@gregrazer",
                     "@petermccoyforsc", "allentown", "@cindyr4nh", "missouri's", "@andreascousins",
                     "@mprnews", "@orsendemocrats", "@modemparty", "@nicolergalloway", "@ncdemparty",
                     "@dougducey", "@sen_chandler", "#scpol", "@corymccray", "#hd71",
                     "#sctweets", "#flapol", "#mtpol", "@senatorbiaggi", "@repandyvargas",
                     "#mileg", "@ohrgopcaucus", "@kimpsonforsc", "@speakervos", "@govtimwalz",
                     "@josejavierjjr", "@kerrydonovansd5", "@colosengop", "@jamieeldridgema", "@ssurovell",
                     "penndot", "@massdems", "@governortomwolf", "@genefortexas", "@govraimondo",
                     "@reginaldbolding", "coloradans", "@misendems", "@govsisolak", "@juliejohnsontx",
                     "@maketheroadny", "@argop", "@carlheastie", "@victoria4texas", "@brianfrosh",
                     "@ohiohousedems", "@ripsullivan48", "#idpol", "@senquezada29", "@tatereeves",
                     "mahalo", "@jd4in29", "#vt", "@kcbecker", "@govkemp",
                     "@jessicaramos", "@govevers", "@govnedlamont", "nyers", "@azcentral",
                     "#nc", "@trwhelan", "#mosen", "kansans", "@mindyforma",
                     "@nickbschroer", "@thomasmcelveen", "hoosier", "@repwalle", "@vasenate",
                     "@erinforyall", "lakeville", "@rachelsb", "@chrishurstva", "pennsylvanians",
                     "@annette_taddeo", "#mi06", "@govholcomb", "@texasdemocrats", "@sylvesterturner",
                     "@adrianmadaro", "@briankempga", "@lizkrueger", "pa's", "@mnstevesimon",
                     "@sam_rasoul", "@jeanneshaheen", "@jenniferwexton", "#wmur", "@cmarianirosa",
                     "#wipolitics", "#connecticut", "@maxwellwise", "@joshstein_", "@postandcourier",
                     "@rtdnews", "@lindabrosenthal", "kentuckians", "@vinceleach", "@repscottholcomb",
                     "@one_colorado", "@repdelozier", "@governordeal", "#mepolitics", "@paulgazelka",
                     "#ca", "@rafaelanchia", "dubuque", "@nicole4nevada", "@woodard4kansas",
                     "@kaohlyvangher", "@senatorhaywood", "@repmattkrause", "@briankavanaghny", "@nchousedems",
                     "@almaforarizona", "@justinbrannan", "@vahouse", "@repbrianking", "@yuhline",
                     "@colo_politics", "@seacoastonline", "@newsobserver", "@lizbethkb", "@speakerstraus",
                     "@repkaykhan", "@lorenaad80", "@sscjocoks", "@dananessel", "@nancymace",
                     "@burrows4tx", "@joannesimonbk52", "@nyc_dot", "@kmuthpasenate44", "@azdemparty",
                     "@ncgop", "sc's", "@mpowersnorrell", "#wv", "edd",
                     "missourians", "@nickieantonio", "@senatorparker", "@govmlg", "@roycoopernc",
                     "#ct", "@c_herring", "@nhpr", "#phled", "@repanniekuster",
                     "ohioans", "@karinhousley", "@nily", "@beccarauschma", "@faithwinterco",
                     "hoosiers", "@mattomalley", "@senatorluz", "#district13", "@senatortomdavis",
                     "@gahousehub", "@renee_unterman", "ducey", "#hailstate", "@debbutlerhd18",
                     "nevadans", "@jerrybrowngov", "@stltoday", "@texasgop", "@repkarenkwan",
                     "@delegateaird", "nj's", "#azsen", "@juanita_brent", "@chazbeasley",
                     "@edwgillespie", "@delmaggie43", "@royblunt", "@repjasonsmith", "@philbryantms",
                     "@rep_trichardson", "wisconsinites", "@sengianaris", "@kenpaxtontx", "@drpanmd",
                     "@dogan4rep", "@lorenasgonzalez", "@davepinto", "@ash_kalra", "@nmalliotakis",
                     "#plan4pa", "@teamtram", "@fitzpatrickmo", "nh's", "@tishjames",
                     "@darrincamilleri", "@gregleding", "@adamebbin", "@jheanellew", "@teamkcp",
                     "@atticascott4ky", "@ohdems", "@evan_low", "@fannkfann", "@chadlivengood",
                     "georgians", "@azgop", "@eric_schmitt", "@gabrielacevero", "#ab5",
                     "@startribune", "@johnfetterman", "@ny1", "@nvassemblydems", "sonoma",
                     "@unionleader", "@govrondesantis", "@govmattbevin", "oklahomans", "@marclevine",
                     "@repfreiberg", "@govofco", "@tjshopeforaz", "annapolis", "oregon's",
                     "@billhaslam", "@charliebakerma", "@governorva", "@ctdems", "@ericlesser",
                     "@emilyvirginok", "#keeptexasred", "@hollyjmitchell", "@tinasmithmn", "nc's",
                     "@jumaanewilliams", "#queens", "manassas", "#nm", "@govherbert",
                     "#nh", "@senatorshaheen", "maricopa", "@patmccrorync", "@terrymcauliffe",
                     "parson", "@gaylegoldin", "@griermartin", "@delegateguzman", "@domoreno",
                     "@reprickhansen", "cruces", "@scott_wiener", "@onetoughnerd", "@nmhousegop",
                     "@fladems", "@zackfinknews", "#ad32", "@athenasalman", "@rontkim",
                     "tennessee's", "az's", "@sierra4az", "@juliacarmel__", "@louisianagov",
                     "@graigmeyer", "@juliancyr", "@repmcclinton", "@governorkayivey", "kalamazoo",
                     "#ia01", "@katrinashealy", "#mindfulness", "@drschwertner", "@espinozadiego19",
                     "@ppadvocacyma", "vermonters", "@mannyfornh", "@troy4nj7", "@govwalker",
                     "beaufort", "@govpritzker", "iowans", "corpus", "@flgovscott",
                     "allegheny", "@dylan_robertsco", "#arkansas", "brownback", "@senatorlorettaw",
                     "@pricefordel95", "alaskans", "tarrant", "r.i", "@ralstonreports",
                     "maryland's", "#ma", "n.c", "@markherringva", "@replizmiranda",
                     "@mariarobinsonma", "@briscoecain", "@jeffjacksonnc", "@govabbott", "@markkeam",
                     "#baltimore", "@massago", "moco", "@patricksvitek", "@iagovernor",
                     "holyoke", "#iapolitics", "@indystar", "@votemarsha", "@vademocrats",
                     "#gameonva", "@repangelaromero", "tallahassee", "@cesarchavezaz", "#puttingpeoplefirst",
                     "@iamjonsantiago", "@sencapito", "#ia04", "@courierjournal", "mpls",
                     "staters", "frankfort", "@hickforco", "md's", "christi",
                     "@govlaurakelly", "@davidpepper", "@kdeleon", "@spencerjcox", "@marthamcsally",
                     "ct's", "#cdnpoli", "@jeremyallenmoss", "@mollybeck", "@tomoliverson",
                     "@jbpritzker", "hogan's", "#kygov", "michiganders", "@texastribune",
                     "fl's", "@mta", "@rep_pendarvis", "@senbowatson", "@danpatrick",
                     "@yvannacancela", "mainers", "@tennessean", "@speakertimjones", "@davidweprin",
                     "@damon_thayer", "#sd24", "@stephaniehowse", "@navarreteaz", "@maura_healey",
                     "montanans", "connecticut's", "ca's", "@biaggi4ny", "@mattbevin",
                     "@sltrib", "@edwardtedjames", "ohio's", "@govandybeshear", "arizona's",
                     "#pa", "@denverpost", "@jpenamelnyk", "pritzker", "@crisantaduran",
                     "@repjocasta", "@cesarjblanco", "@baltimoresun", "@cherylkagan", "californians",
                     "@aarondfordnv", "minnesota's", "beshear", "@collins_neal", "#vermont",
                     "@friendsforbatch", "@kywhitney", "topeka", "wolf's", "@raquelteran",
                     "@james_e_white", "colorado's", "#hb481", "@carlosgsmith", "indiana's",
                     "@buffywicks", "texans", "@brucefranksjr", "@thetnholler", "@fdny",
                     "@jeffrey_sanchez", "foxconn", "pennsylvania's", "@govmurphy", "@catalinacruzny",
                     "ky's", "@stephanielily", "scorpio", "broward", "#hd29",
                     "#yelp", "nashua", "#colorado", "staten", "bevin",
                     "winona", "haverhill", "yorkers", "#fitn", "oklahoma's",
                     "floridians", "wisconsin's", "#demslead", "iowa's", "#arizona",
                     "aiken", "harrisburg", "@ralphnortham", "@peggyflanagan", "#maryland",
                     "@daniele4nv", "#nj", "minnesotan", "#brooklyn", "@jaredpolis",
                     "sacramento", "mn", "@repmarygonzalez", "madigan", "@houstonchron",
                     "#montana", "@ajc", "@rondesantisfl", "@kathykltran", "@beeforgeorgia",
                     "stamford", "ijc", "@govphilscott", "#massachusetts", "@cindypolofl103",
                     "kentucky's", "@nypdnews", "n.h", "lepage", "@iowademocrats",
                     "@detroitnews", "nh", "@ruixuks", "@stlouisblues", "@govmikedewine",
                     "@mattlesser", "#texas", "westchester", "@gcobbhunter", "@gavinnewsom",
                     "ri", "az", "#newmexico", "isd", "@bryanlowry3",
                     "@mallorymcmorrow", "#maine", "denton", "@gretchenwhitmer", "#elpasostrong",
                     "paterson", "@nycmayor", "#wisconsin", "@kimreynoldsia", "@danielforaz",
                     "#georgia", "granite", "#missouri", "#mizzou", "ny's",
                     "@jonhoadley", "wvu", "@goptodd", "maine's", "walz",
                     "@renittashannon", "florida's", "@repharris", "maryland", "@seattletimes",
                     "pa", "texan", "#utah", "@oregongovbrown", "@repandybiggsaz",
                     "stl", "springdale", "@efillercorn", "@senmcsallyaz", "@jsodonoghue",
                     "albuquerque", "@jcarrollfoy", "georgia's", "@jdunnington", "michigan's",
                     "#ohio", "🌵", "@govwhitmer", "mcallen", "tucson",
                     "@xjelliott", "cuomo's", "@freep", "nc", "nm",
                     "@gregabbott_tx", "@iastartingline", "albany", "@annaforflorida", "jersey's",
                     "missouri", "miami-dade", "worcester", "@darshunkendrick", "wv",
                     "@natebell4ar", "@repkclark", "@nygovcuomo", "norwalk", "@dallasnews",
                     "arkansas", "bronx", "massachusetts", "@halaayala", "#letswork",
                     "@wutrain", "@delegatestewart", "tn", "minnesota", "ky",
                     "#mississippi", "lehigh", "@andybeshearky", "@steveyeagernv", "#houston",
                     "#alaska", "@kyrstensinema", "norwich", "utah's", "#elpaso",
                     "queens", "@emiliasykesoh", "@davidcicilline", "roanoke", "baltimore",
                     "abbott", "@govinslee", "#nypd", "@dafna_m", "arizona",
                     "lansing", "fairfax", "fresno", "cod", "#cancelrent",
                     "@senatorspearman", "@leslieherod", "#valeg", "bergen", "ma",
                     "#philly", "@corafaith4mo", "n.j", "wi", "sc",
                     "@chicagosmayor", "juneau", "#northcarolina", "duluth", "california's",
                     "connecticut", "rhode", "@joekennedy", "dewine", "ar",
                     "@marimanoogian", "#pennsylvania", "tennessee", "andover", "george's",
                     "@captmarkkelly", "mcmaster", "endorser", "jay's", "#virginia",
                     "#nevada", "hartford", "@billdeblasio", "#pittsburgh", "@shevrinjones",
                     "indianapolis", "#michigan", "mta", "@cannonfor58", "ks",
                     "@senerikageiss", "86th", "illinois", "md", "s.c",
                     "mo", "nv", "#california", "@newyorkstateag", "utah",
                     "alameda", "@governorbullock", "olympia", "indiana", "#florida",
                     "arroyo", "@summerforpa", "@hawleymo", "rockland", "colorado",
                     "toledo", "hogan", "#boston", "linn", "wa",
                     "desantis", "texas", "#harvey", "tillis", "ca",
                     "newt", "il", "@dmregister", "#kentucky", "#va",
                     "#sd13", "dade", "@jennmcclellanva", "schmitt", "anchorage",
                     "pennsylvania", "greensboro", "ohio", "#yourvoice", "alabama's",
                     "🍌", "@benjealous", "wisconsin", "nevada", "deerfield",
                     "tx", "wichita", "#nyc", "mexicans", "@bostonglobe",
                     "georgia", "virginians", "@nydailynews", "milwaukee", "lamont",
                     "sumter", "hampshire", "trenton", "nj", "newsom",
                     "@carterforva", "#sd20", "#illinois", "montana", "@mattgaetz",
                     "medford", "evers", "york's", "alamo", "oregon",
                     "maine", "nebraska", "winnebago", "okc", "nypd",
                     "idaho", "@sentomcotton", "nova", "@briannaforco", "@samforgeorgia",
                     "ventura", "berger", "aloha", "raleigh", "kansas",
                     "alberta", "louisiana's", "#vaccineswork", "collin", "cooper's",
                     "@markwarner", "kemp", "dekalb", "oklahoma", "hmong",
                     "virginia's", "#alabama", "alaska", "carolinians", "iowa",
                     "cobb", "michigan", "cuomo", "kentucky", "tampa",
                     "mcsally", "nassau", "winfield", "uconn", "mississippi's",
                     "concord", "@pwcdanica", "trudeau", "providence", "upstate",
                     "warwick", "🌮", "moines", "@julieemerson", "northam",
                     "boulder", "@astros", "#iowa", "ga", "#hurricaneirma",
                     "li", "phoenix", "va's", "indy", "florida",
                     "@mrmikeblake", "@timkaine", "fl", "ct", "bethlehem",
                     "richmond", "ia", "nd", "#irma", "louisiana",
                     "@johncornyn", "greenwich", "#hd40", "mexico's", "nashville",
                     "manchester", "coral", "middlesex", "unofficial", "california",
                     "ny", "ab", "@edmarkey", "🍊", "uw",
                     "@govchristie", "mcauliffe", "philly", "marin", "bernardino",
                     "@saragideon", "bonding", "wolf", "reynolds", "rouge",
                     "brooklyn", "hawaiian", "harlem", "clemson", "@sethmoulton",
                     "boise", "nyc", "hays", "diego", "atl",
                     "💎", "austin", "philadelphia", "richland", "mississippi",
                     "fargo", "ak", "boston", "whitmer", "relates",
                     "atlanta", "houston", "jersey", "unc", "85th",
                     "detroit", "vt", "cal", "assemblymember", "hawaii",
                     "#peoplefirst", "quincy", "vermont", "virginia", "jeffco",
                     "@clairecmc", "#redfored", "@scottwalker", "navajo", "carolina's",
                     "csu", "pueblo", "manhattan", "hutchinson", "asm",
                     "#teampete", "@tomcottonar", "alabama", "va", "@cardinals",
                     "durham", "@varatifyera", "hf", "denver", "subway",
                     "hassan", "blasio", "antonio", "sac", "louis",
                     "dallas", "l.a", "workgroup", "bart", "@senwhitehouse",
                     "sioux", "lowell", "miami", "louisville", "clara",
                     "#masen", "parish", "@32bjseiu", "🦠", "minneapolis",
                     "greenville", "reno", "#hb2", "baylor", "memphis",
                     "costa", "helena", "plymouth", "pittsburgh", "fe",
                     "wy", "fulton", "#hurricaneharvey", "knox", "delaware",
                     "evacuations", "wyoming", "twp", "chandler", "vacancy",
                     "merrimack", "pg", "@keithellison", "@packers", "beaver",
                     "@latimes", "york", "asu", "yorker", "baton",
                     "mi", "hb2", "fla", "#flyeaglesfly", "#sd19",
                     "cambridge", "holcomb", "sa", "@ricksantorum", "orlando",
                     "rebate", "riverside", "@chuckgrassley", "portsmouth", "orleans",
                     "🦌", "carolina", "🗽", "cedar", "omaha",
                     "dispatch", "@repcummings", "assemblyman", "mcdaniel", "bucks",
                     "@staceyabrams", "localities", "co-author", "208", "camden",
                     "fairfield", "lancaster", "mexico", "buffalo", "tulsa",
                     "commonwealth's", "evacuation", "des", "beacon", "newton",
                     "amherst", "cooper", "shepherd", "@harrisonjaime", "busch",
                     "paso", "hillsborough", "winchester", "flint", "jacksonville",
                     "@redsox", "angeles", "jamaica", "trout", "baker",
                     "woodbury", "howell", "@clewandowski_", "cincinnati", "vegas",
                     "dayton", "chicago", "clayton", "#dorian", "dominion",
                     "polk", "erie", "containment", "bison", "san",
                     "norfolk", "bridgeport", "williamsburg", "streamed", "#coronavirusupdate",
                     "frederick", "charlotte", "cape", "@andrewgillum", "#happeningnow",
                     "@bakari_sellers", "lynn", "usc", "@sethabramson", "guilford",
                     "@ayannapressley", "irma", "@nypost", "ellison", "dickinson",
                     "authoring", "travis", "jc", "springfield", "@elizabethforma",
                     "🤦🏾‍♀", "buena", "stafford", "keystone", "solitary",
                     "jose", "hudson", "lone", "athens", "@kcstar")
  
  
  
  # get the top 10 words for every topic
  mat <- labelTopics(result, n = 10, frexweight = 0.5)$frex
  
  
  # iterate over every topic
  counter <- 0
  for (i in 1:nrow(mat)) {
    # get the top 10 words for the topic at hand
    words_to_check <- mat[i,]
    
    # if any of the top 10 words of the topic are in one of our state words,
    # or (else if) any of the two word states have both of their words present in the top 10 words
    # then increase the counter by 1
    if (length(intersect(words_to_check, c(single_word_states, abbreviations, twitter_terms) )) > 0 ) {
      counter <- counter + 1
    } else if ( any(vapply(two_word_states_list, FUN = function(x) all(x %in% words_to_check), FUN.VALUE=T))) {
      counter <- counter + 1
    }
    
    # otherwise counter stays the same
  }
  
  return(counter)
  
}

################################################################################
############### Count of the number of state related topics for each model
################################################################################
leg60 <- readRDS("../STM_Models/stm_sm_leg60.RDS")
twts60 <- readRDS("../STM_Models/stm_sm_twts60.RDS")
twts120 <- readRDS("../STM_Models/stm_sm_twts120.RDS")
leg120 <- readRDS("../STM_Models/stm_sm_leg120.RDS")

get_n_state_topics(leg60)  #42
get_n_state_topics(leg120) #71
get_n_state_topics(twts60) #23
get_n_state_topics(twts120) #41

################################################################################
################ Put Into a Dataframe
################################################################################
# Create Vectors
Topics <- c('60-topics','120-topics')
Tweets <- c( "23", "41")
Legislators <- c( "42", "71")

# Create DataFrame
df <- data.frame(Topics,Tweets,Legislators)

# save DataFrame
write.csv(df, "Appendix_Table2.csv") 
